FROM node:16.14
WORKDIR /src
EXPOSE 5123

COPY . .

RUN apt-get update
RUN apt-get install libsqlite3-dev

RUN yarn add sqlite3 --build-from-source --sqlite=/usr --verbose
RUN yarn --verbose

ENV NODE_OPTIONS="--unhandled-rejections=strict"

CMD ["node", "."]